/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error': '#ba1a1a',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed-dim': '#b9c7df',
        'tertiary-fixed': '#ffdbcd',
        'surface-container': '#ededf9',
        'outline-variant': '#c3c6d7',
        'on-tertiary': '#ffffff',
        'primary': '#004ac6',
        'surface-container-high': '#e7e7f3',
        'secondary-container': '#d5e3fc',
        'on-secondary': '#ffffff',
        'primary-container': '#2563eb',
        'tertiary': '#943700',
        'surface-variant': '#e1e2ed',
        'inverse-on-surface': '#f0f0fb',
        'secondary': '#515f74',
        'on-tertiary-container': '#ffede6',
        'on-secondary-fixed-variant': '#3a485b',
        'tertiary-fixed-dim': '#ffb596',
        'inverse-surface': '#2e3039',
        'on-primary': '#ffffff',
        'on-primary-container': '#eeefff',
        'surface': '#faf8ff',
        'surface-tint': '#0053db',
        'on-surface': '#191b23',
        'outline': '#737686',
        'on-surface-variant': '#434655',
        'secondary-fixed': '#d5e3fc',
        'on-secondary-container': '#57657a',
        'background': '#faf8ff',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#003ea8',
        'tertiary-container': '#bc4800',
        'surface-container-highest': '#e1e2ed',
        'surface-container-low': '#f3f3fe',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#00174b',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#0d1c2e',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b4c5ff',
        'surface-bright': '#faf8ff',
        'on-background': '#191b23',
        'surface-dim': '#d9d9e5',
        'on-tertiary-fixed': '#360f00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        // 'full' intentionally not overridden — keeps Tailwind default 9999px for circles/pills
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        gutter: '24px',
        unit: '4px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Assistant', 'system-ui', '-apple-system', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
